package domain.entities.auth;

public enum Permission {
    CREATE_USER,
    DELETE_USER,
    VIEW_QUOTE,
    CREATE_BROKERAGE_ACCOUNT,
    CLOSE_BROKERAGE_ACCOUNT,
    LINK_BROKERAGE_ACCOUNT_TO_EXTERNAL,
    TRANSFER_FUNDS,
    PLACE_TRADE,
    VIEW_PORTFOLIO,
    CREATE_WATCHLIST,
    DELETE_WATCHLIST,
    PUBLISH_WATCHLIST,
    CREATE_ARTICLE,
    VIEW_ARTICLE,
    PUBLISH_ARTICLE,
    VIEW_SECURITY_RATING,
    PUBLISH_SECURITY_RATING
}
