CREATE OR REPLACE PROCEDURE reset_identity_seq (
    p_table_name  IN VARCHAR2,
    p_column_name IN VARCHAR2
)
AS
    v_exists NUMBER;
BEGIN
    -- Check if the table and column exist and is an identity column
    SELECT COUNT(*)
      INTO v_exists
      FROM USER_TAB_IDENTITY_COLS
     WHERE TABLE_NAME = UPPER(p_table_name)
       AND COLUMN_NAME = UPPER(p_column_name);

    IF v_exists = 1 THEN
        -- Reset the identity counter to 1
        EXECUTE IMMEDIATE 'ALTER TABLE ' || p_table_name ||
                          ' MODIFY ' || p_column_name ||
                          ' GENERATED BY DEFAULT AS IDENTITY (START WITH 1)';

        DBMS_OUTPUT.PUT_LINE('Identity column ' || p_table_name || '.' || p_column_name ||
                             ' reset successfully to start with 1.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('No identity column found for ' || p_table_name || '.' || p_column_name);
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error resetting identity column: ' || SQLERRM);
END reset_identity_seq;
/