ALTER TABLE APP_ROLE ADD (
    USER_TYPE_ID NUMBER,
    CONSTRAINT FK_APP_ROLE_USER_TYPE
        FOREIGN KEY (USER_TYPE_ID)
        REFERENCES APP_USER_TYPE (ID)
);

UPDATE APP_ROLE r
SET USER_TYPE_ID = CASE r.NAME
    WHEN 'Admin' THEN (SELECT ID FROM APP_USER_TYPE WHERE NAME = 'EMPLOYEE')
    WHEN 'Analyst' THEN (SELECT ID FROM APP_USER_TYPE WHERE NAME = 'EMPLOYEE')
    WHEN 'PersonalInvestor' THEN (SELECT ID FROM APP_USER_TYPE WHERE NAME = 'CLIENT')
    WHEN 'Public' THEN (SELECT ID FROM APP_USER_TYPE WHERE NAME = 'CLIENT')
    ELSE USER_TYPE_ID
END
WHERE r.NAME IN ('Admin', 'Analyst', 'PersonalInvestor', 'Public');
