-- ============================================
-- SQL Script for APP_USER Entity
-- Oracle Cloud Database
-- Authors: Claude AI, Mateo Vergara
-- ============================================

CREATE TABLE APP_USER (
    -- Primary Key: Database ID, auto-generated
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,

    -- Required Unique Identifier (UUID)
    UUID RAW(16) NOT NULL,

    EMPLOYEE_ID VARCHAR2(50) NULL,
    USERNAME VARCHAR2(100) NOT NULL,
    PERSONAL_EMAIL VARCHAR2(255) NULL,
    EMPLOYEE_EMAIL VARCHAR2(255) NULL,
    FIRST_NAME VARCHAR2(100) NOT NULL,
    MIDDLE_NAME VARCHAR2(100) NULL,
    LAST_NAME VARCHAR2(100) NOT NULL,

    -- Client (Consumer) Password Security Fields
    CLIENT_PASSWORD_HASH VARCHAR2(255) NULL,
    CLIENT_PASSWORD_SALT VARCHAR2(100) NULL,

    -- Employee (Internal Access) Password Security Fields
    EMPLOYEE_PASSWORD_HASH VARCHAR2(255) NULL,
    EMPLOYEE_PASSWORD_SALT VARCHAR2(100) NULL,

    CLIENT_TOTP_SECRET   VARCHAR2(64 CHAR),
    EMPLOYEE_TOTP_SECRET VARCHAR2(64 CHAR)

    -- User Type Flags
    IS_CLIENT    BOOLEAN DEFAULT FALSE NOT NULL,
    IS_EMPLOYEE  BOOLEAN DEFAULT FALSE NOT NULL

    -- Audit Timestamps
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    -- Primary Key Constraint
    CONSTRAINT user_pk PRIMARY KEY (ID),

    -- Unique Constraints
    CONSTRAINT user_uuid_uk UNIQUE (UUID),
    CONSTRAINT user_username_uk UNIQUE (USERNAME),
    CONSTRAINT user_personal_email_uk UNIQUE (PERSONAL_EMAIL),
    CONSTRAINT user_employee_email_uk UNIQUE (EMPLOYEE_EMAIL),
    CONSTRAINT user_employee_id_uk UNIQUE (EMPLOYEE_ID),

    CONSTRAINT user_domain_logic_check CHECK (
        (NOT IS_CLIENT OR (PERSONAL_EMAIL IS NOT NULL AND CLIENT_PASSWORD_HASH IS NOT NULL AND CLIENT_PASSWORD_SALT IS NOT NULL))
    AND (NOT IS_EMPLOYEE OR (EMPLOYEE_ID IS NOT NULL AND EMPLOYEE_EMAIL IS NOT NULL AND EMPLOYEE_PASSWORD_HASH IS NOT NULL AND EMPLOYEE_PASSWORD_SALT IS NOT NULL))
    AND (IS_CLIENT OR IS_EMPLOYEE)
    ),

    -- Non-blank string validations (matching Java constructor logic)
    CONSTRAINT user_non_empty_username CHECK (
        TRIM(USERNAME) IS NOT NULL AND TRIM(USERNAME) <> ''
    ),
    CONSTRAINT user_non_empty_firstname CHECK (
        TRIM(FIRST_NAME) IS NOT NULL AND TRIM(FIRST_NAME) <> ''
    ),
    CONSTRAINT user_non_empty_lastname CHECK (
        TRIM(LAST_NAME) IS NOT NULL AND TRIM(LAST_NAME) <> ''
    ),
    CONSTRAINT user_non_empty_personal_email CHECK (
        PERSONAL_EMAIL IS NULL OR TRIM(PERSONAL_EMAIL) <> ''
    ),
    CONSTRAINT user_non_empty_employee_email CHECK (
        EMPLOYEE_EMAIL IS NULL OR TRIM(EMPLOYEE_EMAIL) <> ''
    ),
    CONSTRAINT user_non_empty_employee_id CHECK (
        EMPLOYEE_ID IS NULL OR TRIM(EMPLOYEE_ID) <> ''
    ),

    -- Email format validation (basic regex pattern)
    CONSTRAINT user_email_format CHECK (
        (PERSONAL_EMAIL IS NULL OR
         REGEXP_LIKE(PERSONAL_EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'))
        AND
        (EMPLOYEE_EMAIL IS NULL OR
         REGEXP_LIKE(EMPLOYEE_EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'))
    )
);

-- Performance Indexes (based on UserRepository query methods)
-- Note: UUID, USERNAME, PERSONAL_EMAIL, EMPLOYEE_EMAIL, EMPLOYEE_ID already have
-- unique constraints which Oracle automatically indexes, so no additional indexes needed.
-- Adding composite index for common query patterns:
CREATE INDEX idx_user_created_at ON APP_USER (CREATED_AT);
CREATE INDEX idx_user_lastname_firstname ON APP_USER (LAST_NAME, FIRST_NAME);

-- Trigger for automatic UPDATED_AT timestamp maintenance
CREATE OR REPLACE TRIGGER app_user_updated_at_trigger
    BEFORE UPDATE ON APP_USER
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

-- Table and Column Documentation
COMMENT ON TABLE APP_USER IS 'Stores user accounts, including personal and employee profiles.';
COMMENT ON COLUMN APP_USER.ID IS 'Primary key, generated identity.';
COMMENT ON COLUMN APP_USER.UUID IS 'Globally unique identifier for the user.';
COMMENT ON COLUMN APP_USER.EMPLOYEE_ID IS 'Unique employee identifier (required if employee email is provided).';
COMMENT ON COLUMN APP_USER.EMPLOYEE_EMAIL IS 'Employee work email (required if employee ID is provided).';
COMMENT ON COLUMN APP_USER.PERSONAL_EMAIL IS 'Personal email address (at least one email required).';
COMMENT ON COLUMN APP_USER.USERNAME IS 'Unique system login identifier.';
COMMENT ON COLUMN APP_USER.FIRST_NAME IS 'User first name.';
COMMENT ON COLUMN APP_USER.MIDDLE_NAME IS 'User middle name (optional).';
COMMENT ON COLUMN APP_USER.LAST_NAME IS 'User last name.';
COMMENT ON COLUMN APP_USER.CLIENT_PASSWORD_HASH IS 'Hashed client/consumer password.';
COMMENT ON COLUMN APP_USER.CLIENT_PASSWORD_SALT IS 'Salt for client password hash.';
COMMENT ON COLUMN APP_USER.EMPLOYEE_PASSWORD_HASH IS 'Hashed employee password for internal access.';
COMMENT ON COLUMN APP_USER.EMPLOYEE_PASSWORD_SALT IS 'Salt for employee password hash.';
COMMENT ON COLUMN APP_USER.CREATED_AT IS 'Timestamp when record was created.';
COMMENT ON COLUMN APP_USER.UPDATED_AT IS 'Timestamp when record was last updated.';

COMMIT;