-- ============================================
-- USER_TYPE Table (Enum: CLIENT, EMPLOYEE)
-- ============================================
CREATE TABLE USER_TYPE (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    TYPE_NAME VARCHAR2(50) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT user_type_pk PRIMARY KEY (ID),
    CONSTRAINT user_type_name_uk UNIQUE (TYPE_NAME),

    CONSTRAINT user_type_non_empty_name CHECK (
        TRIM(TYPE_NAME) IS NOT NULL AND TRIM(TYPE_NAME) <> ''
    ),

    -- Enforce enum values from application UserType enum
    CONSTRAINT user_type_valid_values CHECK (
        TYPE_NAME IN ('CLIENT', 'EMPLOYEE')
    )
);

COMMENT ON TABLE USER_TYPE IS 'User type classification matching UserType enum';
COMMENT ON COLUMN USER_TYPE.TYPE_NAME IS 'User type: CLIENT or EMPLOYEE';

-- ============================================
-- Insert enum values into USER_TYPE table
-- ============================================
INSERT INTO USER_TYPE (TYPE_NAME)
VALUES ('CLIENT');

INSERT INTO USER_TYPE (TYPE_NAME)
VALUES ('EMPLOYEE');