-- Insert PUBLIC_USER role permissions
INSERT INTO APP_ROLE_PERMISSION (ROLE_ID, PERMISSION_ID)
SELECT r.ID, p.ID
FROM APP_ROLE r
JOIN APP_PERMISSION p ON p.NAME IN (
    'VIEW_QUOTE',
    'VIEW_ARTICLE',
    'VIEW_SECURITY_RATING',
    'CREATE_WATCHLIST',
    'DELETE_WATCHLIST'
)
WHERE r.NAME = 'Public';

-- Insert PERSONAL_INVESTOR_ROLE permissions
INSERT INTO APP_ROLE_PERMISSION (ROLE_ID, PERMISSION_ID)
SELECT r.ID, p.ID
FROM APP_ROLE r
JOIN APP_PERMISSION p ON p.NAME IN (
    'VIEW_QUOTE',
    'VIEW_ARTICLE',
    'VIEW_SECURITY_RATING',
    'CREATE_WATCHLIST',
    'DELETE_WATCHLIST',
    'CREATE_BROKERAGE_ACCOUNT',
    'CLOSE_BROKERAGE_ACCOUNT',
    'LINK_BROKERAGE_ACCOUNT_TO_EXTERNAL',
    'TRANSFER_FUNDS',
    'PLACE_TRADE',
    'VIEW_PORTFOLIO'
)
WHERE r.NAME = 'PersonalInvestor';

-- Insert ANALYST_ROLE permissions
INSERT INTO APP_ROLE_PERMISSION (ROLE_ID, PERMISSION_ID)
SELECT r.ID, p.ID
FROM APP_ROLE r
JOIN APP_PERMISSION p ON p.NAME IN (
    'VIEW_QUOTE',
    'VIEW_ARTICLE',
    'VIEW_SECURITY_RATING',
    'CREATE_WATCHLIST',
    'DELETE_WATCHLIST',
    'CREATE_ARTICLE',
    'PUBLISH_ARTICLE',
    'PUBLISH_WATCHLIST',
    'PUBLISH_SECURITY_RATING'
)
WHERE r.NAME = 'Analyst';

-- Assign all permissions to Admin
INSERT INTO APP_ROLE_PERMISSION (ROLE_ID, PERMISSION_ID)
SELECT r.ID, p.ID
FROM APP_ROLE r
CROSS JOIN APP_PERMISSION p
WHERE r.NAME = 'Admin'
  AND NOT EXISTS (
      SELECT 1 FROM APP_ROLE_PERMISSION rp
      WHERE rp.ROLE_ID = r.ID
        AND rp.PERMISSION_ID = p.ID
  );