package com.marketpilot.domain.entities.auth;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.HashSet;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

@DisplayName("User Name Validation Tests")
class UserTest {
    private User testUser;

    @BeforeEach
    void setUp() {
        testUser = new User("ab123456", "johnmdoe", "johnmdoe@outlook.com",
                "johnmdoe@company.com", "John", "M", "Doe");
    }

    @Test
    void constructor_throwsForNullEmployeeIdAndNonNullEmployeeEmail() {
        assertThrows(IllegalArgumentException.class, () ->
                new User(null, "johnmdoe", "johnmdoe@outlook.com",
                        "johnmdoe@company.com","John", "M", "Doe"));
    }

    @Test
    void constructor_throwsForNonNullEmployeeIdAndNullEmployeeEmail() {
        assertThrows(IllegalArgumentException.class, () ->
                new User("ab123456", "johnmdoe", "johnmdoe@outlook.com",
                        null,"John", "M", "Doe"));
    }

    @Test
    void constructor_throwsForBlankEmployeeId() {
        assertThrows(IllegalArgumentException.class, () ->
                new User("   ", "johnmdoe", "johnmdoe@outlook.com",
                        "johnmdoe@company.com","John", "M", "Doe"));
    }

    @Test
    void constructor_throwsForNullUsername() {
        assertThrows(IllegalArgumentException.class, () ->
                        new User("ab123456", null, "johnmdoe@outlook.com",
                                "johnmdoe@company.com","John", "M", "Doe"),
                "Expected constructor to throw for null first name");
    }

    @Test
    void constructor_throwsForBlankUsername() {
        assertThrows(IllegalArgumentException.class, () ->
                        new User("ab123456", "     ", "johnmdoe@outlook.com",
                                "johnmdoe@company.com","John", "M", "Doe"),
                "Expected constructor to throw for null first name");
    }

    @Test
    void constructor_throwsForNullPersonalAndEmployeeEmails() {
        assertThrows(IllegalArgumentException.class, () ->
                        new User("ab123456", "johnmdoe", null,
                                null,"John", "M", "Doe"),
                "Expected constructor to throw for null personalEmail and null employeeEmail");
    }

    @Test
    void constructor_throwsForBlankPersonalEmail() {
        assertThrows(IllegalArgumentException.class, () ->
                        new User("ab123456", "johnmdoe", "      ",
                                null,"John", "M", "Doe"),
                "Expected constructor to throw for blank personalEmail");
    }

    // generated by Claude.ai
    @Test
    void constructor_throwsForInvalidPersonalEmailPatterns() {
        // Missing @ symbol
        assertThrows(IllegalArgumentException.class, () ->
                        new User("ab123456", "johnmdoe", "userexample.com",
                                null,"John", "M", "Doe"),
                "Expected constructor to throw for email missing @ symbol");

        // Multiple @ symbols
        assertThrows(IllegalArgumentException.class, () ->
                        new User("ab123456", "johnmdoe", "user@@example.com",
                                null,"John", "M", "Doe"),
                "Expected constructor to throw for email with multiple @ symbols");

        // Empty local part (before @)
        assertThrows(IllegalArgumentException.class, () ->
                        new User("ab123456", "johnmdoe", "@example.com",
                                null,"John", "M", "Doe"),
                "Expected constructor to throw for email with empty local part");

        // Empty domain part (after @)
        assertThrows(IllegalArgumentException.class, () ->
                        new User("ab123456", "johnmdoe", "user@",
                                null,"John", "M", "Doe"),
                "Expected constructor to throw for email with empty domain part");

        // Consecutive dots in local part
        assertThrows(IllegalArgumentException.class, () ->
                        new User("ab123456", "johnmdoe", "user..name@example.com",
                                null,"John", "M", "Doe"),
                "Expected constructor to throw for email with consecutive dots in local part");

        // Local part starting with dot
        assertThrows(IllegalArgumentException.class, () ->
                        new User("ab123456", "johnmdoe", ".user@example.com",
                                null,"John", "M", "Doe"),
                "Expected constructor to throw for email with local part starting with dot");

        // Local part ending with dot
        assertThrows(IllegalArgumentException.class, () ->
                        new User("ab123456", "johnmdoe", "user.@example.com",
                                null,"John", "M", "Doe"),
                "Expected constructor to throw for email with local part ending with dot");

        // Invalid character (space) in local part
        assertThrows(IllegalArgumentException.class, () ->
                        new User("ab123456", "johnmdoe", "user name@example.com",
                                null,"John", "M", "Doe"),
                "Expected constructor to throw for email with space in local part");

        // Domain without TLD
        assertThrows(IllegalArgumentException.class, () ->
                        new User("ab123456", "johnmdoe", "user@localhost",
                                null,"John", "M", "Doe"),
                "Expected constructor to throw for email with domain missing TLD");

        // Domain starting with hyphen
        assertThrows(IllegalArgumentException.class, () ->
                        new User("ab123456", "johnmdoe", "user@-example.com",
                                null,"John", "M", "Doe"),
                "Expected constructor to throw for email with domain starting with hyphen");

        // Domain ending with hyphen
        assertThrows(IllegalArgumentException.class, () ->
                        new User("ab123456", "johnmdoe", "user@example-.com",
                                null,"John", "M", "Doe"),
                "Expected constructor to throw for email with domain ending with hyphen");

        // Consecutive dots in domain
        assertThrows(IllegalArgumentException.class, () ->
                        new User("ab123456", "johnmdoe", "user@example..com",
                                null,"John", "M", "Doe"),
                "Expected constructor to throw for email with consecutive dots in domain");

        // Local part too long (over 64 characters)
        String longLocalPart = "a".repeat(65);
        assertThrows(IllegalArgumentException.class, () ->
                        new User("ab123456", "johnmdoe", longLocalPart + "@example.com",
                                null,"John", "M", "Doe"),
                "Expected constructor to throw for email with local part exceeding 64 characters");

        // Domain too long (over 253 characters total)
        String longDomain = "a".repeat(250) + ".com";
        assertThrows(IllegalArgumentException.class, () ->
                        new User("ab123456", "johnmdoe", "user@" + longDomain,
                                null,"John", "M", "Doe"),
                "Expected constructor to throw for email with domain exceeding 253 characters");
    }

    // generated by Claude.ai
    @Test
    void constructor_acceptsValidPersonalEmailPatterns() {
        // Basic valid email
        assertDoesNotThrow(() ->
                        new User(null, "johnmdoe", "user@example.com",
                                null,"John", "M", "Doe"),
                "Valid basic email should not throw exception");

        // Email with dots in local part
        assertDoesNotThrow(() ->
                        new User(null, "johnmdoe", "john.doe@company.org",
                                null,"John", "M", "Doe"),
                "Valid email with dots in local part should not throw exception");

        // Email with underscore and plus
        assertDoesNotThrow(() ->
                        new User(null, "johnmdoe", "test_user+tag@example.com",
                                null,"John", "M", "Doe"),
                "Valid email with underscore and plus should not throw exception");

        // Email with numbers
        assertDoesNotThrow(() ->
                        new User(null, "johnmdoe", "user123@example.com",
                                null,"John", "M", "Doe"),
                "Valid email with numbers should not throw exception");

        // Email with subdomain
        assertDoesNotThrow(() ->
                        new User(null, "johnmdoe", "user@mail.example.com",
                                null,"John", "M", "Doe"),
                "Valid email with subdomain should not throw exception");

        // Email with hyphen in domain
        assertDoesNotThrow(() ->
                        new User(null, "johnmdoe", "user@my-company.com",
                                null,"John", "M", "Doe"),
                "Valid email with hyphen in domain should not throw exception");

        // Short but valid email
        assertDoesNotThrow(() ->
                        new User(null, "johnmdoe", "a@b.co",
                                null,"John", "M", "Doe"),
                "Valid short email should not throw exception");
    }

    @Test
    void constructor_throwsForBlankEmployeeEmail() {
        assertThrows(IllegalArgumentException.class, () ->
                        new User("ab123456", "johnmdoe", null,
                                " ","John", "M", "Doe"),
                "Expected constructor to throw for blank employeeEmail");
    }

    // generated by Claude.ai
    @Test
    void constructor_throwsForInvalidEmployeeEmailPatterns() {
        // Missing @ symbol
        assertThrows(IllegalArgumentException.class, () ->
                        new User("ab123456", "johnmdoe", null, "userexample.com",
                                "John", "M", "Doe"),
                "Expected constructor to throw for employee email missing @ symbol");

        // Multiple @ symbols
        assertThrows(IllegalArgumentException.class, () ->
                        new User("ab123456", "johnmdoe", null, "user@@example.com",
                                "John", "M", "Doe"),
                "Expected constructor to throw for employee email with multiple @ symbols");

        // Empty local part (before @)
        assertThrows(IllegalArgumentException.class, () ->
                        new User("ab123456", "johnmdoe", null, "@example.com",
                                "John", "M", "Doe"),
                "Expected constructor to throw for employee email with empty local part");

        // Empty domain part (after @)
        assertThrows(IllegalArgumentException.class, () ->
                        new User("ab123456", "johnmdoe", null, "user@",
                                "John", "M", "Doe"),
                "Expected constructor to throw for employee email with empty domain part");

        // Consecutive dots in local part
        assertThrows(IllegalArgumentException.class, () ->
                        new User("ab123456", "johnmdoe", null, "user..name@example.com",
                                "John", "M", "Doe"),
                "Expected constructor to throw for employee email with consecutive dots in local part");

        // Local part starting with dot
        assertThrows(IllegalArgumentException.class, () ->
                        new User("ab123456", "johnmdoe", null, ".user@example.com",
                                "John", "M", "Doe"),
                "Expected constructor to throw for employee email with local part starting with dot");

        // Local part ending with dot
        assertThrows(IllegalArgumentException.class, () ->
                        new User("ab123456", "johnmdoe", null, "user.@example.com",
                                "John", "M", "Doe"),
                "Expected constructor to throw for employee email with local part ending with dot");

        // Invalid character (space) in local part
        assertThrows(IllegalArgumentException.class, () ->
                        new User("ab123456", "johnmdoe", null, "user name@example.com",
                                "John", "M", "Doe"),
                "Expected constructor to throw for employee email with space in local part");

        // Domain without TLD
        assertThrows(IllegalArgumentException.class, () ->
                        new User("ab123456", "johnmdoe", null, "user@localhost",
                                "John", "M", "Doe"),
                "Expected constructor to throw for employee email with domain missing TLD");

        // Domain starting with hyphen
        assertThrows(IllegalArgumentException.class, () ->
                        new User("ab123456", "johnmdoe", null, "user@-example.com",
                                "John", "M", "Doe"),
                "Expected constructor to throw for employee email with domain starting with hyphen");

        // Domain ending with hyphen
        assertThrows(IllegalArgumentException.class, () ->
                        new User("ab123456", "johnmdoe", null, "user@example-.com",
                                "John", "M", "Doe"),
                "Expected constructor to throw for employee email with domain ending with hyphen");

        // Consecutive dots in domain
        assertThrows(IllegalArgumentException.class, () ->
                        new User("ab123456", "johnmdoe", null, "user@example..com",
                                "John", "M", "Doe"),
                "Expected constructor to throw for employee email with consecutive dots in domain");

        // Local part too long (over 64 characters)
        String longLocalPart = "a".repeat(65);
        assertThrows(IllegalArgumentException.class, () ->
                        new User("ab123456", "johnmdoe", null, longLocalPart + "@example.com",
                                "John", "M", "Doe"),
                "Expected constructor to throw for employee email with local part exceeding 64 characters");

        // Domain too long (over 253 characters total)
        String longDomain = "a".repeat(250) + ".com";
        assertThrows(IllegalArgumentException.class, () ->
                        new User("ab123456", "johnmdoe", null, "user@" + longDomain,
                                "John", "M", "Doe"),
                "Expected constructor to throw for employee email with domain exceeding 253 characters");
    }

    // generated by Claude.ai
    @Test
    void constructor_acceptsValidEmployeeEmailPatterns() {
        // Valid basic email
        assertDoesNotThrow(() ->
                        new User("ab123456", "johnmdoe", null, "user@example.com",
                                "John", "M", "Doe"),
                "Valid employee email with null first email should not throw exception");

        // Email with dots in local part
        assertDoesNotThrow(() ->
                        new User("ab123456", "johnmdoe", null, "john.doe@company.org",
                                "John", "M", "Doe"),
                "Valid employee email with dots in local part should not throw exception");

        // Email with underscore and plus
        assertDoesNotThrow(() ->
                        new User("ab123456", "johnmdoe", null, "test_user+tag@example.com",
                                "John", "M", "Doe"),
                "Valid employee email with underscore and plus should not throw exception");

        // Email with numbers
        assertDoesNotThrow(() ->
                        new User("ab123456", "johnmdoe", null, "user123@example.com",
                                "John", "M", "Doe"),
                "Valid employee email with numbers should not throw exception");

        // Email with subdomain
        assertDoesNotThrow(() ->
                        new User("ab123456", "johnmdoe", null, "user@mail.example.com",
                                "John", "M", "Doe"),
                "Valid employee email with subdomain should not throw exception");

        // Email with hyphen in domain
        assertDoesNotThrow(() ->
                        new User("ab123456", "johnmdoe", null, "user@my-company.com",
                                "John", "M", "Doe"),
                "Valid employee email with hyphen in domain should not throw exception");

        // Short but valid email
        assertDoesNotThrow(() ->
                        new User("ab123456", "johnmdoe", null, "a@b.co",
                                "John", "M", "Doe"),
                "Valid short employee email should not throw exception");
    }

    @Test
    void constructor_throwsForNullFirstName() {
        assertThrows(IllegalArgumentException.class, () ->
                        new User("ab123456", "johnmdoe", "johnmdoe@outlook.com",
                                "johnmdoe@company.com",null, "M", "Doe"),
                "Expected constructor to throw for null first name");
    }

    @Test
    void constructor_throwsForBlankFirstName() {
        assertThrows(IllegalArgumentException.class, () ->
                new User("ab123456", "johnmdoe", "johnmdoe@outlook.com",
                        "johnmdoe@company.com","      ", "M", "Doe"));
    }

    @Test
    void constructor_throwsForNullLastName() {
        assertThrows(IllegalArgumentException.class, () ->
                new User("ab123456", "johnmdoe", "johnmdoe@outlook.com",
                        "johnmdoe@company.com","John", "M", null));
    }

    @Test
    void constructor_throwsForBlankLastName() {
        assertThrows(IllegalArgumentException.class, () ->
                new User("ab123456", "johnmdoe", "johnmdoe@outlook.com",
                        "johnmdoe@company.com","John", "M", ""));
    }

    @Test
    void getUUID_throwsIfUUIDIsNull() {
        assertThrows(IllegalStateException.class, () ->
                testUser.getUUID());
    }

    @Test
    void getUUID_doesNotThrowIfUUIDIsNotNull() {
        testUser.setUUID(UUID.fromString("550e8400-e29b-41d4-a716-446655440000"));
        assertDoesNotThrow(() -> testUser.getUUID());
    }

    @Test
    void isClient_throwsIfUserIsNotAClientAndIsNotAnEmployee() {
        assertThrows(IllegalStateException.class, () ->
                testUser.isClient());
    }

    @Test
    void isClient_doesNotThrowIfUserIsAClient() {
        testUser.setClient(true);
        assertDoesNotThrow(() -> testUser.isClient());
    }

    @Test
    void isClient_doesNotThrowIfUserIsAnEmployee() {
        testUser.setEmployee(true);
        assertDoesNotThrow(() -> testUser.isClient());
    }

    @Test
    void isEmployee_throwsIfUserIsNotAClientAndIsNotAnEmployee() {
        assertThrows(IllegalStateException.class, () ->
                testUser.isEmployee());
    }

    @Test
    void isEmployee_doesNotThrowIfUserIsAnEmployee() {
        testUser.setEmployee(true);
        assertDoesNotThrow(() -> testUser.isEmployee());
    }

    @Test
    void isEmployee_doesNotThrowIfUserIsAClient() {
        testUser.setClient(true);
        assertDoesNotThrow(() -> testUser.isEmployee());
    }

    @Test
    void hasRole_returnsFalseIfUserDoesNotHaveRole() {
        testUser.grantRole(TestRoles.PERSONAL_INVESTOR_ROLE);
        assertFalse(testUser.hasRole(Role.RoleName.Analyst));
    }

    @Test
    void hasRole_returnsTrueIfUserHasRole() {
        testUser.grantRole(TestRoles.PERSONAL_INVESTOR_ROLE);
        assertTrue(testUser.hasRole(Role.RoleName.PersonalInvestor));
    }

    @Test
    void setUUID_throwsForNullUUID() {
        assertThrows(IllegalArgumentException.class, () ->
                testUser.setUUID(null));
    }

    @Test
    void setUUID_throwsIfVersionIsNot4() {
        System.out.println(UUID.fromString("f81d4fae-7dec-21d0-a765-00a0c91e6bf6").version());
        assertThrows(IllegalArgumentException.class, () ->
                testUser.setUUID(UUID.fromString("f81d4fae-7dec-21d0-a765-00a0c91e6bf6")));
    }

    @Test
    void setUUID_doesNotThrowForValidUUID() {
        assertDoesNotThrow(() -> testUser.setUUID(UUID.fromString("550e8400-e29b-41d4-a716-446655440000")));
    }

    @Test
    void setEmployeeId_throwsIfEmployeeIdIsNull() {
        assertThrows(IllegalArgumentException.class, () ->
                testUser.setEmployeeId(null));
    }

    @Test
    void setEmployeeId_throwsIfEmployeeIdIsBlank() {
        assertThrows(IllegalArgumentException.class, () ->
                testUser.setEmployeeId("        "));
    }

    @Test
    void setClientPasswordHash_throwsIfHashIsNull() {
        assertThrows(IllegalArgumentException.class, () ->
                testUser.setClientPasswordHash(null));
    }

    @Test
    void setClientPasswordHash_throwsIfHashIsBlank() {
        assertThrows(IllegalArgumentException.class, () ->
                testUser.setClientPasswordHash("       "));
    }

    @Test
    void setEmployeePasswordHash_throwsIfHashIsNull() {
        assertThrows(IllegalArgumentException.class, () ->
                testUser.setEmployeePasswordHash(null));
    }

    @Test
    void setEmployeePasswordHash_throwsIfHashIsBlank() {
        assertThrows(IllegalArgumentException.class, () ->
                testUser.setEmployeePasswordHash("       "));
    }

    @Test
    void grantRole_throwsForNullUserRolesSet() {
        assertThrows(IllegalArgumentException.class, () ->
                testUser.grantRole(null));
    }

    @Test
    void setPersonalEmail_throwsIfPersonalEmailIsNull() {
        assertThrows(IllegalArgumentException.class, () ->
                testUser.setPersonalEmail(null));
    }

    @Test
    void setPersonalEmail_throwsIfPersonalEmailIsBlank() {
        assertThrows(IllegalArgumentException.class, () ->
                testUser.setPersonalEmail("        "));
    }

    @Test
    void setEmployeeEmail_throwsIfEmployeeEmailIsNull() {
        assertThrows(IllegalArgumentException.class, () ->
                testUser.setEmployeeEmail(null));
    }

    @Test
    void setEmployeeEmail_throwsIfEmployeeEmailIsBlank() {
        assertThrows(IllegalArgumentException.class, () ->
                testUser.setEmployeeEmail("        "));
    }

    @Test
    void setFirstName_throwsForNullArg() {
        assertThrows(IllegalArgumentException.class, () -> testUser.setFirstName(null));
    }

    @Test
    void setFirstName_throwsForBlankArg() {
        assertThrows(IllegalArgumentException.class, () -> testUser.setFirstName("     "));
    }

    @Test
    void setLastName_throwsForNullString() {
        assertThrows(IllegalArgumentException.class, () -> testUser.setLastName(null));
    }

    @Test
    void setLastName_throwsForBlankString() {
        assertThrows(IllegalArgumentException.class, () -> testUser.setLastName("\n"));
    }
}
