package com.marketpilot.adapters.persistence.migration;

import com.marketpilot.adapters.persistence.Batch;
import com.marketpilot.adapters.persistence.JdbcExecutor;
import com.marketpilot.adapters.persistence.Param;

import java.util.Set;

import static com.marketpilot.adapters.persistence.Param.stringP;

public class EnumSeederUtil {
    private final static Set<String> allowedTables = Set.of(
            "app_permission",
            "app_role"
    );

    protected static <E> void seed(Class<E> enumClass, String targetTableName) {
        createTableIfNotExists(targetTableName);
        syncEnumToTable(enumClass, targetTableName);
    }

    protected static void createTableIfNotExists(String targetTableName) {
        if(!allowedTables.contains(targetTableName.toLowerCase()))
            return;

        String sql = "CREATE TABLE IF NOT EXISTS " + targetTableName.toUpperCase() +
            """
             (
                ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
                NAME VARCHAR2(100) NOT NULL UNIQUE,
                CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
            );
            """;

        JdbcExecutor.executeUpdate(sql);
    }

    protected static <E> void syncEnumToTable(Class<E> enumClass, String targetTableName) {
        if(!allowedTables.contains(targetTableName.toLowerCase()))
            return;

        E[] enumConstants = enumClass.getEnumConstants();
        String tableNameUpper = targetTableName.toUpperCase();

        String insertSql = String.format("""
            INSERT INTO %s (NAME, CREATED_AT, UPDATED_AT)
            SELECT ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
            FROM dual
            WHERE NOT EXISTS (
                SELECT 1 FROM %s WHERE NAME = ?
            )
            """, tableNameUpper, tableNameUpper);

        Batch[] batches = new Batch[enumConstants.length];
        for (int i = 0; i < enumConstants.length; i++) {
            batches[i] = new Batch(stringP(1, enumConstants[i].toString()),
                    stringP(2, enumConstants[i].toString()));
        }

        JdbcExecutor.executeUpdateBatch(insertSql, batches);


        StringBuilder deleteSql = new StringBuilder("DELETE FROM " + tableNameUpper + " WHERE NAME NOT IN (");
        Param[] params = new Param[enumConstants.length];
        for (int i = 0; i < enumConstants.length; i++) {
            deleteSql.append("?");
            params[i] = stringP(i + 1, enumConstants[i].toString());
            if (i < enumConstants.length - 1) {
                deleteSql.append(", ");
            }
        }
        deleteSql.append(")");

        JdbcExecutor.executeUpdate(deleteSql.toString(), params);
    }
}