package com.marketpilot.adapters.persistence.migration;

import com.marketpilot.adapters.persistence.jdbc.Batch;
import com.marketpilot.adapters.persistence.jdbc.JdbcExecutor;
import com.marketpilot.adapters.persistence.jdbc.Param;

import java.sql.SQLException;
import java.util.List;
import java.util.Set;

import static com.marketpilot.adapters.persistence.jdbc.Param.stringP;

public class EnumSeederUtil {
    private final static Set<String> allowedTables = Set.of(
            "app_permission",
            "app_role",
            "app_user_type",
            "app_user_status",
            "mfatype"
    );

    protected static <E> void seed(Class<E> enumClass, String targetTableName) {
        createTableIfNotExists(targetTableName);
        syncEnumToTable(enumClass, targetTableName);
    }

    protected static void createTableIfNotExists(String targetTableName) {
        if(!allowedTables.contains(targetTableName.toLowerCase()))
            return;

        String tableNameUpper = targetTableName.toUpperCase();

        String sql = String.format("""
            CREATE TABLE IF NOT EXISTS %s
            (
                ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
                NAME VARCHAR2(100) NOT NULL UNIQUE,
                CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                CONSTRAINT PK_%s PRIMARY KEY (ID)
            );
            """, tableNameUpper, tableNameUpper);

        try {
            JdbcExecutor.executeUpdate(sql);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    protected static <E> void syncEnumToTable(Class<E> enumClass, String targetTableName) {
        if(!allowedTables.contains(targetTableName.toLowerCase()))
            return;

        try {
            JdbcExecutor.executeUpdate(String.format("""
                DELETE FROM %s
                """, targetTableName));
        } catch (SQLException e) {
            e.printStackTrace();
        }

        resetIdSequence(targetTableName);

        E[] enumConstants = enumClass.getEnumConstants();
        String tableNameUpper = targetTableName.toUpperCase();

        String insertSql = String.format("""
            INSERT INTO %s (NAME, CREATED_AT, UPDATED_AT)
            SELECT ?, SYSTIMESTAMP, SYSTIMESTAMP
            FROM dual
            WHERE NOT EXISTS (
                SELECT 1 FROM %s WHERE NAME = ?
            )
            """, tableNameUpper, tableNameUpper);

        Batch[] batches = new Batch[enumConstants.length];
        for (int i = 0; i < enumConstants.length; i++) {
            batches[i] = new Batch(stringP(1, enumConstants[i].toString()),
                    stringP(2, enumConstants[i].toString()));
        }

        JdbcExecutor.executeUpdateBatch(insertSql, batches);
    }

    private static void resetIdSequence(String targetTableName) {
        try {
            JdbcExecutor.executeUpdateProc("reset_identity_seq", false,
                    stringP(1, targetTableName), stringP(2, "ID"));
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}