package com.marketpilot.adapters.persistence.migration;

import com.marketpilot.adapters.persistence.JdbcExecutor;
import com.marketpilot.adapters.persistence.Param;
import com.marketpilot.domain.entities.auth.Permission;

import static com.marketpilot.adapters.persistence.Param.stringP;

public class EnumSeederUtil {
    protected static <E> void seed(Class<E> enumClass, String targetTableName) {
        createTableIfNotExists(targetTableName);
        insertEnumValues(enumClass, targetTableName);
    }

    private static void createTableIfNotExists(String targetTableName) {
        String createTableSql = """
            CREATE TABLE IF NOT EXISTS (?) (
                ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
                NAME VARCHAR2(100) NOT NULL UNIQUE,
                CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
            );
            """;

        JdbcExecutor.executeUpdate(createTableSql, stringP(1, targetTableName));
    }

    private static <E> void insertEnumValues(Class<E> enumClass, String targetTableName) {
        E[] enumConstants = enumClass.getEnumConstants();

        StringBuilder sqlBuilder = new StringBuilder("INSERT INTO (?) (NAME) VALUES ");
        // Add placeholders for each permission
        for (int i = 0; i < enumConstants.length; i++) {
            sqlBuilder.append("(?)");
            if (i < enumConstants.length - 1) {
                sqlBuilder.append(", ");
            }
        }

        Param[] params = new Param[enumConstants.length + 1];
        params[0] = stringP(1, targetTableName);
        for (int i = 0; i < enumConstants.length; i++)
            params[i] = stringP(i + 2, enumConstants[i].toString());

        JdbcExecutor.executeUpdate(sqlBuilder.toString(), params);
    }
}