package com.marketpilot.adapters.persistence.migration;

import com.marketpilot.adapters.persistence.JdbcExecutor;
import com.marketpilot.adapters.persistence.Param;
import com.marketpilot.domain.entities.auth.Permission;

public class PermissionSeeder {

    public static void main(String[] args) {
        try {
            createTableIfNotExists();
            insertPermissions();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private static void createTableIfNotExists() {
        String createTableSql = """
            CREATE TABLE IF NOT EXISTS APP_PERMISSION (
                ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
                PERMISSION_NAME VARCHAR2(100) NOT NULL UNIQUE,
                CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
            );
            """;

        JdbcExecutor.executeUpdate(createTableSql);
    }

    private static void insertPermissions() {
        Permission[] permissions = Permission.values();

        StringBuilder sqlBuilder = new StringBuilder("INSERT INTO APP_PERMISSION (permission_name) VALUES ");

        // Add placeholders for each permission
        for (int i = 0; i < permissions.length; i++) {
            sqlBuilder.append("(?)");
            if (i < permissions.length - 1) {
                sqlBuilder.append(", ");
            }
        }

        Param[] params = new Param[permissions.length];
        for (int i = 0; i < permissions.length; i++)
            params[i] = Param.stringP(i + 1, permissions[i].name());

        JdbcExecutor.executeUpdate(sqlBuilder.toString(), params);
    }
}