CREATE TABLE APP_USER_AUTH (
    USER_ID                          NUMBER PRIMARY KEY,
    IS_CLIENT                        BOOLEAN DEFAULT FALSE NOT NULL,
    CLIENT_PASSWORD_HASH             RAW(200) NULL,
    CLIENT_REGISTRATION_CODE         VARCHAR2(16),
    CLIENT_REGISTRATION_EXPIRATION   TIMESTAMP NULL,
    CLIENT_TOTP_SECRET               VARCHAR2(64),
    CLIENT_USER_STATUS_ID            NUMBER(2),
    IS_EMPLOYEE                      BOOLEAN DEFAULT FALSE NOT NULL,
    EMPLOYEE_PASSWORD_HASH           RAW(200) NULL,
    EMPLOYEE_REGISTRATION_CODE       VARCHAR2(16),
    EMPLOYEE_REGISTRATION_EXPIRATION TIMESTAMP NULL,
    EMPLOYEE_TOTP_SECRET             VARCHAR2(64),
    EMPLOYEE_USER_STATUS_ID          NUMBER(2),

    CONSTRAINT FK_APP_USER_AUTH FOREIGN KEY (USER_ID) REFERENCES APP_USER(ID)
);