    create table if not exists APP_ROLE (
        role_name number(3,0) check ((role_name between 0 and 3)),
        user_type number(3,0) check ((user_type between 0 and 1)),
        id number(19,0) generated by default as identity,
        primary key (id)
    )
;
    create table if not exists APP_ROLE_PERMISSION (
        permissions number(3,0) check ((permissions between 0 and 16)),
        role_id number(19,0) not null
    )
;
    create table if not exists APP_USER (
        client_profile_id number(19,0) unique,
        employee_profile_id number(19,0) unique,
        id number(19,0) generated by default as identity,
        uuid raw(16) not null unique,
        first_name varchar2(50 char) not null,
        last_name varchar2(50 char) not null,
        middle_name varchar2(50 char),
        username varchar2(50 char) not null,
        primary key (id)
    )
;
    create table if not exists APP_USER_ROLE (
        role_id number(19,0) not null,
        user_id number(19,0) not null,
        primary key (role_id, user_id)
    )
;
    create table if not exists CLIENT_PROFILE (
        id number(19,0) generated by default as identity,
        email varchar2(255 char) not null unique,
        primary key (id)
    )
;
    create table if not exists EMPLOYEE_PROFILE (
        id number(19,0) generated by default as identity,
        email varchar2(255 char) not null unique,
        employee_id varchar2(255 char) not null unique,
        primary key (id)
    )
;
    alter table APP_ROLE_PERMISSION 
       add constraint FKtdbppbotsunq353i15j683hfh 
       foreign key (role_id) 
       references APP_ROLE
;
    alter table APP_USER 
       add constraint FKorpw8pbfcvgh5bpnmqyjt8x36 
       foreign key (client_profile_id) 
       references CLIENT_PROFILE
;
    alter table APP_USER 
       add constraint FKdo89erbw0odfqtbvhiptrto9o 
       foreign key (employee_profile_id) 
       references EMPLOYEE_PROFILE
;
    alter table APP_USER_ROLE 
       add constraint FKdl4wlha7hrp0gtwicv9sr2ki9 
       foreign key (role_id) 
       references APP_ROLE
;
    alter table APP_USER_ROLE 
       add constraint FK5a2x3vrshctvys85qti3927r7 
       foreign key (user_id) 
       references APP_USER
;

create table if not exists APP_USER_AUTH (
    USER_ID                          NUMBER PRIMARY KEY,
    UUID RAW(16)                     NOT NULL,
    IS_CLIENT                        BOOLEAN DEFAULT FALSE NOT NULL,
    CLIENT_PASSWORD_HASH             RAW(200) NULL,
    CLIENT_REGISTRATION_CODE         VARCHAR2(16),
    CLIENT_REGISTRATION_EXPIRATION   TIMESTAMP DEFAULT (SYSTIMESTAMP + INTERVAL '30' MINUTE) NULL,
    CLIENT_TOTP_SECRET               VARCHAR2(64),
    CLIENT_USER_STATUS_ID            NUMBER(2),
    IS_EMPLOYEE                      BOOLEAN DEFAULT FALSE NOT NULL,
    EMPLOYEE_PASSWORD_HASH           RAW(200) NULL,
    EMPLOYEE_REGISTRATION_CODE       VARCHAR2(16),
    EMPLOYEE_REGISTRATION_EXPIRATION TIMESTAMP NULL,
    EMPLOYEE_TOTP_SECRET             VARCHAR2(64),
    EMPLOYEE_USER_STATUS_ID          NUMBER(2),

    CONSTRAINT FK_APP_USER_AUTH FOREIGN KEY (USER_ID) REFERENCES APP_USER(ID)
);